require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'spec/support/**/*'
    - 'tmp/**/*'

RSpec/DescribedClass:
  Enabled: false
